apiVersion: v1
kind: Service
metadata:
  name: techfest
  namespace: techfest
  labels:
    app: techfest
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: techfest
    tier: frontend
